# Generated by Django 3.2.13 on 2022-06-29 11:06

from django.db import migrations, models
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=video_encoding.fields.VideoField(default=0, height_field='height', upload_to='', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Test'),
        ),
    ]
