# Generated by Django 3.2.13 on 2022-07-18 12:31

from django.db import migrations
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20220629_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Kino', 'verbose_name_plural': 'Kinolar'},
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=video_encoding.fields.VideoField(height_field='height', upload_to='movie/%Y/%m/%d', verbose_name='Video file', width_field='width'),
        ),
    ]
